# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
gems: [jekyll-paginate]
gems: [jekyll-paginate, jekyll-gist]

# Setup
title:            El Sitio Hyde de Angie
tagline:          'Montado con Jekyll'
description:      'Un intento de montar un sitio <a href="http://jekyllrb.com" target="_blank">Jekyll</a>. Hecho por <a href="https://twitter.com/A_N3Z" target="_blank">@A_N3Z</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Angie Neslin'
  url:            https://twitter.com/A_N3Z

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
